# Site settings
title: "TextLog"
description: "Minimalist Jekyll theme for documentation site"
baseurl: "/blog" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "http://olivierbinette.ca"
author: "John Doe"

# Build settings
kramdown:
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:

plugins:

remote_theme: heiswayi/textlog
